### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by PiranhaHunter** [abij/az-account-switcher#8]
Switch [2]: 6
Traceback (most recent call last):
  File "/Users/varadha.s/Library/Python/3.8/bin/az-switch", line 8, in <module>
    sys.exit(main())
  File "/Users/varadha.s/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/varadha.s/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/varadha.s/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/varadha.s/Library/Python/3.8/lib/python/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/varadha.s/Library/Python/3.8/lib/python/site-packages/az_account_switcher/az_account_switcher.py", line 41, in main
    _, subscription_id = get_azure_cli_credentials()
  File "/Users/varadha.s/Library/Python/3.8/lib/python/site-packages/azure/common/credentials.py", line 138, in get_azure_cli_credentials
    raise NotImplementedError(
NotImplementedError: The public API of azure-cli-core has been deprecated starting 2.21.0, and this method can no longer return a valid credential. If you need to still use this method, you need to install 'azure-cli-core<2.21.0'. You may corrupt data if you use current CLI and old azure-cli-core. See also: https://aka.ms/azsdk/python/identity/migration

**Comment by abij** [comment]
Released new version, please `pip install -U az-account-switcher` and try again!

**Comment by PiranhaHunter** [comment]
Awesome! Thanks a lot!
